import { TColor } from './types/util-types';

export enum EColor {
  global            = 'hsla(0, 0%, 15%, 1)',
  globalLight1      = 'hsla(0, 0%, 20%, 1)',
  globalDark1       = 'hsla(0, 0%, 10%, 1)',
  globalContrast    = 'hsla(0, 100%, 100%, 1)',
  primary           = 'hsla(200, 37%, 52%, 1)',
  primaryLight1     = 'hsla(200, 37%, 60%, 1)',
  primaryDark1      = 'hsla(200, 37%, 58%, 1)',
  primaryContrast   = 'hsla(0, 100%, 100%, 1)',
  secondary         = 'hsla(100, 37%, 52%, 1)',
  secondaryLight1   = 'hsla(100, 37%, 58%, 1)',
  secondaryDark1    = 'hsla(100, 37%, 45%, 1)',
  secondaryContrast = 'hsla(0, 100%, 100%, 1)',
  tertiary          = 'hsla(400, 38%, 35%, 1)',
  tertiaryLight1    = 'hsla(400, 38%, 40%, 1)',
  tertiaryDark1     = 'hsla(400, 38%, 30%, 1)',
  tertiaryContrast  = 'hsla(0, 100%, 100%, 1)',
  success           = 'hsla(83, 46%, 47%, 1)',
  successLight1     = 'hsla(83, 46%, 52%, 1)',
  successDark1      = 'hsla(83, 46%, 40%, 1)',
  successContrast   = 'hsla(0, 100%, 100%, 1)',
  disabled          = 'hsla(0, 0%, 87%, 1)',
  disabledLight1    = 'hsla(0, 0%, 92%, 1)',
  disabledDark1     = 'hsla(0, 0%, 70%, 1)',
  disabledContrast  = 'hsla(0, 100%, 100%, 1)',
  warning           = 'hsla(7, 66%, 57%, 1)',
  warningLight1     = 'hsla(7, 66%, 62%, 1)',
  warningDark1      = 'hsla(7, 66%, 52%, 1)',
  warningContrast   = 'hsla(0, 100%, 100%, 1)',
  failure           = 'hsla(7, 66%, 57%, 1)',
  failureLight1     = 'hsla(7, 66%, 62%, 1)',
  failureDark1      = 'hsla(7, 66%, 52%, 1)',
  failureContrast   = 'hsla(0, 100%, 100%, 1)',
  loading           = 'hsla(47, 94%, 66%, 1)',
  loadingLight1     = 'hsla(47, 94%, 70%, 1)',
  loadingDark1      = 'hsla(47, 94%, 60%, 1)',
  loadingContrast   = 'hsla(0, 100%, 100%, 1)',
  info              = 'hsla(207, 64%, 48%, 1)',
  infoLight1        = 'hsla(207, 64%, 55%, 1)',
  infoDark1         = 'hsla(207, 64%, 42%, 1)',
  infoContrast      = 'hsla(0, 100%, 100%, 1)',
  white             = 'hsla(0, 100%, 100%, 1)',
  black             = 'hsla(0, 0%, 0%, 1)',
  neutral           = 'hsla(0, 0%, 40%, 1)',
  neutralLight1     = 'hsla(0, 0%, 50%, 1)',
  neutralLight2     = 'hsla(0, 0%, 60%, 1)',
  neutralLight3     = 'hsla(0, 0%, 70%, 1)',
  neutralDark1      = 'hsla(0, 0%, 30%, 1)',
  neutralDark2      = 'hsla(0, 0%, 20%, 1)',
  neutralDark3      = 'hsla(0, 0%, 10%, 1)'
}

export const COLOR: any = {
  global            : 'global',
  globalLight1      : 'globalLight1',
  globalDark1       : 'globalDark1',
  globalContrast    : 'globalContrast',
  primary           : 'primary',
  primaryLight1     : 'primaryLight1',
  primaryDark1      : 'primaryDark1',
  primaryContrast   : 'primaryContrast',
  secondary         : 'secondary',
  secondaryLight1   : 'secondaryLight1',
  secondaryDark1    : 'secondaryDark1',
  secondaryContrast : 'secondaryContrast',
  tertiary          : 'tertiary',
  tertiaryLight1    : 'tertiaryLight1',
  tertiaryDark1     : 'tertiaryDark1',
  tertiaryContrast  : 'tertiaryContrast',
  success           : 'success',
  successLight1     : 'successLight1',
  successDark1      : 'successDark1',
  successContrast   : 'successContrast',
  disabled          : 'disabled',
  disabledLight1    : 'disabledLight1',
  disabledDark1     : 'disabledDark1',
  disabledContrast  : 'disabledContrast',
  warning           : 'warning',
  warningLight1     : 'warningLight1',
  warningDark1      : 'warningDark1',
  warningContrast   : 'warningContrast',
  failure           : 'failure',
  failureLight1     : 'failureLight1',
  failureDark1      : 'failureDark1',
  failureContrast   : 'failureContrast',
  loading           : 'loading',
  loadingLight1     : 'loadingLight1',
  loadingDark1      : 'loadingDark1',
  loadingContrast   : 'loadingContrast',
  info              : 'info',
  infoLight1        : 'infoLight1',
  infoDark1         : 'infoDark1',
  infoContrast      : 'infoContrast',
  white             : 'white',
  black             : 'black',
  neutral           : 'neutral',
  neutralLight1     : 'neutralLight1',
  neutralLight2     : 'neutralLight2',
  neutralLight3     : 'neutralLight3',
  neutralDark1      : 'neutralDark1',
  neutralDark2      : 'neutralDark2',
  neutralDark3      : 'neutralDark3'
}